version: '2'
services:
    jhipster20180530-app:
        image: jhipster20180530
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://jhipster20180530-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=jhipster20180530
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipster20180530-mongodb:
        extends:
            file: mongodb.yml
            service: jhipster20180530-mongodb
