version: '2'
services:
    jhipster20180530-mongodb:
        image: mongo:3.4.10
        ports:
            - "27017:27017"
        command: mongos --configdb jhipster20180530-mongodb-config
    jhipster20180530-mongodb-node:
        build:
            context: .
            dockerfile: mongodb/MongoDB.Dockerfile
        command: mongod --replSet rs1 --noprealloc --smallfiles
    jhipster20180530-mongodb-config:
        image: mongo:3.4.10
        container_name: jhipster20180530-mongodb-config
        command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
